In [4]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [51]:
%run ./per_main.py -t 1 -l 0.25 mode2 -d ./data/problema_real1.txt


Exec mode 2
0
EX: [1 0] GOT: [0 0]
Weights Before [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]
Weights After [[ 0.05   0.025  0.025  0.025  0.05   0.025  0.05   0.025  0.025]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]]
Updated: True
**********
1
EX: [1 0] GOT: [0 0]
Weights Before [[ 0.05   0.025  0.025  0.025  0.05   0.025  0.05   0.025  0.025]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]]
Weights After [[ 0.1    0.05   0.05   0.05   0.1    0.05   0.125  0.05   0.05 ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]]
Updated: True
**********
2
EX: [1 0] GOT: [0 0]
Weights Before [[ 0.1    0.05   0.05   0.05   0.1    0.05   0.125  0.05   0.05 ]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]]
Weights After [[ 0.225  0.075  0.075  0.075  0.15   0.075  0.175  0.075  0.075]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.   ]]
Updated: True
**********
3
EX: [0 1] G

Updated: False
**********
100
EX: [1 0] GOT: [1 0]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225  0.175  0.175  0.275  0.475  0.05 ]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225  0.175  0.175  0.275  0.475  0.05 ]]
Updated: False
**********
101
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225  0.175  0.175  0.275  0.475  0.05 ]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225  0.175  0.175  0.275  0.475  0.05 ]]
Updated: False
**********
102
EX: [0 1] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225  0.175  0.175  0.275  0.475  0.05 ]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225

Updated: False
**********
293
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225  0.175  0.175  0.275  0.475  0.05 ]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225  0.175  0.175  0.275  0.475  0.05 ]]
Updated: False
**********
294
EX: [1 0] GOT: [1 0]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225  0.175  0.175  0.275  0.475  0.05 ]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225  0.175  0.175  0.275  0.475  0.05 ]]
Updated: False
**********
295
EX: [0 1] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225  0.175  0.175  0.275  0.475  0.05 ]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.325  0.35   0.4    0.225

Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
473
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
474
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
475
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3  

Updated: False
**********
645
EX: [0 1] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
646
EX: [0 1] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
647
EX: [0 1] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3  

Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
134
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
135
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: Fals

 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
314
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
315
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
316
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1 

506
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
507
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Updated: False
**********
508
EX: [1 0] GOT: [1 1]
Weights Before [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5    0.075]]
Weights After [[ 0.275  0.15   0.1    0.1    0.225  0.1    0.2    0.1    0.1  ]
 [ 0.425  0.375  0.425  0.3    0.2    0.3    0.325  0.5

UnboundLocalError: local variable 'len_in' referenced before assignment

In [ ]:
import dataset
import ada_network as ada
import numpy as np

ds = dataset.Dataset()

ds.load("./data/problema_real1.txt")

#ds.errors(results=np.zeros(ds.output.shape))
#print("***")
#ds.errors(results=ds.output)
#print("***")

input_size = ds.input_size

adaline = ada.AdaNetwork()
