In [4]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [41]:
%run ./per_main.py -t 0.2 -l 0.25 mode2 -d ./data/problema_real1.txt


Exec mode 2
index: 0
[0 0] -> [1 0]
[ 0.2  0.1  0.1  0.1  0.2  0.1  0.2  0.1  0.1] | 0.0 | 0 | 1 |
index: 1
index: 2
index: 3
index: 4
index: 5
index: 6
index: 7
index: 8
index: 9
index: 10
index: 11
index: 12
index: 13
index: 14
index: 15
index: 16
index: 17
index: 18
index: 19
index: 20
index: 21
index: 22
index: 23
index: 24
index: 25
index: 26
index: 27
index: 28
index: 29
index: 30
index: 31
index: 32
index: 33
index: 34
index: 35
index: 36
index: 37
index: 38
index: 39
index: 40
index: 41
index: 42
index: 43
index: 44
index: 45
index: 46
index: 47
index: 48
index: 49
index: 50
index: 51
index: 52
index: 53
index: 54
index: 55
index: 56
index: 57
index: 58
index: 59
index: 60
index: 61
index: 62
index: 63
index: 64
index: 65
index: 66
index: 67
index: 68
index: 69
index: 70
index: 71
index: 72
index: 73
index: 74
index: 75
index: 76
index: 77
index: 78
index: 79
index: 80
index: 81
index: 82
index: 83
index: 84
index: 85
index: 86
index: 87
index: 88
index: 89
index: 90
index: 91


index: 579
index: 580
index: 581
index: 582
index: 583
index: 584
index: 585
index: 586
index: 587
index: 588
index: 589
index: 590
index: 591
index: 592
index: 593
index: 594
index: 595
index: 596
index: 597
index: 598
index: 599
index: 600
index: 601
index: 602
index: 603
index: 604
index: 605
index: 606
index: 607
index: 608
index: 609
index: 610
index: 611
index: 612
index: 613
index: 614
index: 615
index: 616
index: 617
index: 618
index: 619
index: 620
index: 621
index: 622
index: 623
index: 624
index: 625
index: 626
index: 627
index: 628
index: 629
index: 630
index: 631
index: 632
index: 633
index: 634
index: 635
index: 636
index: 637
index: 638
index: 639
index: 640
index: 641
index: 642
index: 643
index: 644
index: 645
index: 646
index: 647
index: 648
index: 649
index: 650
index: 651
index: 652
index: 653
index: 654
index: 655
index: 656
index: 657
index: 658
index: 659
index: 660
index: 661
index: 662
index: 663
index: 664
index: 665
index: 666
index: 667
index: 668
index: 669

[1 1] -> [0 1]
[ 1.   0.4  0.6  0.4  0.5  1.   0.7  0.1  0.1] | 0.25 | 1 | 0 |
index: 333
[1 1] -> [0 1]
[ 0.8  0.8  0.9  0.4  0.5  1.   0.7  0.8  0.1] | 0.25 | 1 | 0 |
index: 334
[1 1] -> [0 1]
[ 0.8  1.   1.   0.7  1.   1.   0.7  0.3  0.8] | 0.25 | 1 | 0 |
index: 335
[1 1] -> [1 0]
[ 0.5  0.7  0.7  0.1  0.5  0.8  0.3  0.4  0.1] | 0.25 | 1 | 0 |
index: 336
[1 1] -> [0 1]
[ 1.   1.   1.   0.1  0.6  0.1  0.2  0.8  0.1] | 0.25 | 1 | 0 |
index: 337
[1 1] -> [1 0]
[ 0.2  0.1  0.1  0.1  0.2  0.1  0.3  0.1  0.1] | 0.25 | 1 | 0 |
index: 338
[1 1] -> [0 1]
[ 1.   0.3  0.3  1.   0.2  1.   0.7  0.3  0.3] | 0.25 | 1 | 0 |
index: 339
[1 1] -> [1 0]
[ 0.6  0.8  0.8  0.1  0.3  0.4  0.3  0.7  0.1] | 0.25 | 1 | 0 |
index: 340
[1 1] -> [0 1]
[ 0.8  1.   1.   1.   0.8  1.   1.   0.7  0.3] | 0.25 | 1 | 0 |
index: 341
[1 1] -> [1 0]
[ 0.3   0.1   0.1   0.1   0.2   0.35  0.3   0.1   0.1 ] | 0.25 | 1 | 0 |
index: 342
[1 1] -> [1 0]
[ 0.1  0.1  0.1  0.1  0.2  0.1  0.1  0.1  0.1] | 0.25 | 1 | 0 |
index: 343
[

UnboundLocalError: local variable 'len_in' referenced before assignment

In [ ]:
import dataset
import ada_network as ada
import numpy as np

ds = dataset.Dataset()

ds.load("./data/problema_real1.txt")

#ds.errors(results=np.zeros(ds.output.shape))
#print("***")
#ds.errors(results=ds.output)
#print("***")

input_size = ds.input_size

adaline = ada.AdaNetwork()
